# Generated by Django 3.2.13 on 2022-06-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('specialisation', models.CharField(max_length=25)),
                ('labo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('departement', models.CharField(max_length=20)),
                ('commune', models.CharField(max_length=25)),
                ('ecosystem', models.CharField(max_length=15)),
                ('researcher', models.ManyToManyField(to='mybiodata.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('biosample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybiodata.biosample')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybiodata.species')),
            ],
        ),
        migrations.AddField(
            model_name='biosample',
            name='sampleData',
            field=models.ManyToManyField(through='mybiodata.SampleData', to='mybiodata.Species'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybiodata.zoneofstudy'),
        ),
    ]
