# Generated by Django 3.2.13 on 2022-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybiodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='date',
            field=models.DateField(),
        ),
    ]
